"""add observability models

Revision ID: 51421c9d8e7f
Revises: 671dd27c0a7b
Create Date: 2026-07-24 12:51:22.117158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51421c9d8e7f'
down_revision: Union[str, Sequence[str], None] = '671dd27c0a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lambda_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lambda_id'], ['lambda_functions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_lambda_id'), 'ai_recommendations', ['lambda_id'], unique=False)
    op.create_table('cloudwatch_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lambda_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('log_stream_name', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('log_timestamp', sa.DateTime(), nullable=False),
    sa.Column('ingestion_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lambda_id'], ['lambda_functions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_cloudwatch_logs_lambda_id'), 'cloudwatch_logs', ['lambda_id'], unique=False)
    op.create_table('cloudwatch_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lambda_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('metric_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lambda_id'], ['lambda_functions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloudwatch_metrics_lambda_id'), 'cloudwatch_metrics', ['lambda_id'], unique=False)
    op.add_column('lambda_functions', sa.Column('function_arn', sa.String(length=500), nullable=False))
    op.add_column('lambda_functions', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('lambda_functions', sa.Column('version', sa.String(length=50), nullable=False))
    op.add_column('lambda_functions', sa.Column('package_type', sa.String(length=50), nullable=False))
    op.add_column('lambda_functions', sa.Column('log_group', sa.String(length=500), nullable=False))
    op.add_column('lambda_functions', sa.Column('revision_id', sa.String(length=100), nullable=False))
    op.add_column('lambda_functions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('lambda_functions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('lambda_functions', 'architecture',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_lambda_functions_id'), table_name='lambda_functions')
    op.create_unique_constraint(None, 'lambda_functions', ['function_arn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lambda_functions', type_='unique')
    op.create_index(op.f('ix_lambda_functions_id'), 'lambda_functions', ['id'], unique=False)
    op.alter_column('lambda_functions', 'architecture',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('lambda_functions', 'updated_at')
    op.drop_column('lambda_functions', 'created_at')
    op.drop_column('lambda_functions', 'revision_id')
    op.drop_column('lambda_functions', 'log_group')
    op.drop_column('lambda_functions', 'package_type')
    op.drop_column('lambda_functions', 'version')
    op.drop_column('lambda_functions', 'description')
    op.drop_column('lambda_functions', 'function_arn')
    op.drop_index(op.f('ix_cloudwatch_metrics_lambda_id'), table_name='cloudwatch_metrics')
    op.drop_table('cloudwatch_metrics')
    op.drop_index(op.f('ix_cloudwatch_logs_lambda_id'), table_name='cloudwatch_logs')
    op.drop_table('cloudwatch_logs')
    op.drop_index(op.f('ix_ai_recommendations_lambda_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    # ### end Alembic commands ###
