"""create lambda functions table

Revision ID: 671dd27c0a7b
Revises: 
Create Date: 2026-07-22 17:06:10.838856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671dd27c0a7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lambda_functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('runtime', sa.String(length=100), nullable=False),
    sa.Column('handler', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=500), nullable=False),
    sa.Column('memory_size', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('last_modified', sa.String(length=100), nullable=False),
    sa.Column('code_size', sa.Integer(), nullable=False),
    sa.Column('architecture', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('function_name')
    )
    op.create_index(op.f('ix_lambda_functions_id'), 'lambda_functions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lambda_functions_id'), table_name='lambda_functions')
    op.drop_table('lambda_functions')
    # ### end Alembic commands ###
